[pytest]
testpaths =
    test_text_importer.py
    test_qt_helpers.py
    test_database_extensions.py
    test_core_modules.py
    test_spell_check.py
    tests
norecursedirs =
    .git
    .pytest_cache
    build
    dist
    release
    vendor
    _MEI*
    .build_tools
    star_graph_enhancement
